### ISSUE TITLE
TypeError: Cannot read property 'android' of null

### ISSUE THREAD

**Issue by Sartori-RIA** [nstudio/nativescript-loading-indicator#2]
hi, i have a shared component with loadspinner, and this component is used only inside two pages  to service http requests, one work fine, other receive the error "TypeError: Cannot read property 'android' of null". 
the component without error is inside tabview BUT in submodule with lazy loading

the component with error is inside TabView in my app.component, this error occurrence when try to use show() method. if i comment show() method call, the source works fine

```typescript 
class PetListComponent {

  private loader: LoadingIndicator = new LoadingIndicator();

  fetchPets() {
     this.loader.show({message: t('loading_fetching_pets')});
     // rest of code
  }
}
```

any idea for whats this error occurrence ?

**Comment by bradmartin** [comment]
Best guess, is the actual instance of `loader` is not the same when it's being accessed in the second page (submodule).

**Comment by nikoTM** [comment]
@Sartori-RIA make sure you are not calling it earlier than `OnInit`

**Comment by Sartori-RIA** [comment]
@nikoTM I'm trying to call inside `AfterViewInit` and make `loader` receive null after `hide()`. Inside submodule works fine but inside my `app.component` inside `tabview` throws  error
obs: before I was using inside `OnInit` and to test i change to `AfterViewInit`
```typescript


    ngAfterViewInit(): void {
      this.fetchPets();
    }

    private fetchPets(): void {
        let loader = new LoadingIndicator();
        const [t] = useT();
        loader.show({message: t('loading_fetching_pets')});
        this.pets$ = this.petService.all();
        this.pets$.subscribe(() => {
            loader.hide();
            loader = null;
        }, (error) => {
            loader.hide();
            loader = null;
            console.error(error)
        }
   }
```

**Comment by Sartori-RIA** [comment]
maybe helps, my tabview is using lazy-loading to tabs, and this component is using inside `zapetTab`

```typescript

const routes: Routes = [
{
        path: 'default',
        component: TabsComponent,
        children: [
            {
                path: 'guardian',
                outlet: 'guardianTab',
                component: NSEmptyOutletComponent,
                loadChildren: '~/app/guardian/guardian.module#GuardianModule',
            }, {
                path: 'zapet',
                outlet: 'zapetTab',
                component: NSEmptyOutletComponent,
                loadChildren: '~/app/zapet/zapet.module#ZapetModule',
            }, {
                path: 'review',
                outlet: 'reviewTab',
                component: NSEmptyOutletComponent,
                loadChildren: '~/app/review/review.module#ReviewModule',
            }
        ]
    }
];
```

**Comment by amlibtest** [comment]
I have a very similar problem (I'm sorry if this was the wrong place to write this, I don't know if it would be better to create another issue)

```sh
JS: **ERROR**  Error: Uncaught (in promise): TypeError: Cannot read property 'android' of undefined
JS: TypeError: Cannot read property 'android' of undefined
JS:     at LoadingIndicator.push.../node_modules/@nstudio/nativescript-loading-indicator/loading-indicator.js.LoadingIndicator._createPopOver file:///node_modules/@nstudio/nativescript-loading-indicator/loading-indicator.js:217:0
JS:     at LoadingIndicator.push.../node_modules/@nstudio/nativescript-loading-indicator/loading-indicator.js.LoadingIndicator.show file:///node_modules/@nstudio/nativescript-loading-indicator/loading-indicator.js:38:0
```

This error is pointing to this line

```ts
var view = frame_1.topmost().android.rootViewGroup || frame_1.topmost().currentPage.android;
```

My code was working with the previous version, but I added the changes:

```ts
import { LoadingIndicator, Mode, OptionsCommon } from '@nstudio/nativescript-loading-indicator';

export class Test{

        loadingIndicator: LoadingIndicator;
	public constructor(){
                  this.loadingIndicator = new LoadingIndicator();
                  ...
         }

    public showLoadingIndicator(msg, cancel=false){
        this.loadingIndicator.show({ 
            message : msg,
            mode: Mode.Indeterminate,
            android: {
                cancelable: cancel
            }
        });
    }

...
}
```

**Comment by edyrkaj** [comment]
Hi,
try to install from node packages:
`npm i tns-platform-declarations`

After installing package, the main thing is to create a references.d.ts file in the root of your project with the following:

```
/// <reference path="./node_modules/tns-platform-declarations/ios.d.ts" />
/// <reference path="./node_modules/tns-platform-declarations/android.d.ts" />
```

**Comment by Sartori-RIA** [comment]
hi @edyrkaj with your solution,  in iOS everything works very well, but in android don't

**Comment by edyrkaj** [comment]
@Sartori-RIA did you tried to remove / add platform from beginning? You can post here what is the next error on your side ;)

**Comment by Sartori-RIA** [comment]
@edyrkaj I try removing: node_modules, hooks and platforms
the error i get is just `TypeError: Cannot read property 'android' of undefined` with no stack trace :/

**Comment by NathanWalker** [comment]
This appears to be related to androidx changes and can occur when the loadingindicator is called early during a boot cycle especially with angular integrations. The android setup needs to be revised and cleaned up to resolve this condition.

/cc @bradmartin @triniwiz

**Comment by lee-devopa** [comment]
I'm also getting this issue. this might be of use to the fixer:

> ERROR in node_modules/@nstudio/nativescript-loading-indicator/index.d.ts(77,10): error TS2304: Cannot find name 'UIView'.
node_modules/@nstudio/nativescript-loading-indicator/index.d.ts(85,10): error TS2503: Cannot find namespace 'android'.

> System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to start activity ComponentInfo{com.company.appname/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.appname/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Main entry is missing. App cannot be started. Verify app bootstrap.
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1242)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1122)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1109)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1089)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1081)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:19)
System.err:     at android.app.Activity.performCreate(Activity.java:7136)
System.err:     at android.app.Activity.performCreate(Activity.java:7127)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
System.err:     ... 11 more

**Comment by nikoTM** [comment]
@Sartori-RIA @edyrkaj it should be working without installing platform-declarations, try adding `"skipLibCheck": true` to your `tsconfig.json -> compilerOptions`. Although, the error mentioned in the initial comment sounds like a runtime error, so this is not a solution, just a workaround so you don't have to install platform declarations.

**Comment by Sartori-RIA** [comment]
@nikoTM I'm already using `skiLibCheck` in my `tsconfig.json`
```son

{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "skipLibCheck": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es6",
            "dom",
            "esnext",
            "es2015.iterable"
        ],
        "baseUrl": ".",
        "paths": {
            "~/*": [
                "src/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms"
    ]
}

```

**Comment by david-mart** [comment]
I had the same issue, loader was failing when loader was called very early in the app loading cycle. My workaround for now

```
let loader = new LoadingIndicator();

const loaderOptions = {
  ios: {
    userInteractionEnabled: false,
    dimBackground: true,
    backgroundColor: "#000000",
    color: "#FFF"
  }
};

export const showLoader = message => {
  try {
    loader.show(R.mergeDeepLeft(loaderOptions, { message }));
  } catch (error) {
    console.log(error);
  }
};

export const hideLoader = () => {
  try {
    loader.hide();
  } catch (error) {
    console.log(error);
  }
};
```

**Comment by RajkumarRepo** [comment]
I'm also face the same issue in android when update native script 6.0

**Comment by GrEg00z** [comment]
From my side, the problem only happen when I put my app in the background (in pause), and when I resume the app :
 - if the app is still awaken, there is no problem with the loader
 - if the app was killed by gc, the app is restarted from 0 and the loader will not working at all, while getting the error  `Cannot read property 'android' of undefined`  when I call the show() method

So the problem on the loader seems to come from the restart on application, when the app is already in pause in the background

**Comment by erkanarslan** [comment]
I also have this problem with Android. On iOS, it works fine. I use NS with Angular.

I show the loading indicator on the ngOnInit method of the first page shown when app starts.
I tried calling the show method with delay in setTimeout to check if something is not initialized.

- If I try a delay of 1 second, it works.
- If I try a delay of 100 ms, I get a different error:
````
JS: ERROR Error: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
JS:     android.view.ViewRootImpl.setView(ViewRootImpl.java:798)
JS:     android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
JS:     android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
JS:     android.widget.PopupWindow.invokePopup(PopupWindow.java:1434)
JS:     android.widget.PopupWindow.showAtLocation(PopupWindow.java:1203)
JS:     android.widget.PopupWindow.showAtLocation(PopupWindow.java:1170)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1083)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1063)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:1055)
JS:     com.tns.gen.java.lang.Runnable.run(Runnable.java:17)
JS:     android.os.Handler.handleCallback(Handler.java:873)
JS:     android.os.Handler.dispatchMess...
````
This plugin worked in the previous repository. But I upgraded to NS 6 and also switched to this repository. Since then, I have this problem.

**Comment by Unity-G** [comment]
Same issue here:

```
JS: ERROR TypeError: Cannot read property 'android' of null

JS: ERROR CONTEXT {
JS:   "view": {
JS:     "def": {
JS:       "nodeFlags": 37863425,
JS:       "rootNodeFlags": 33554433,
JS:       "nodeMatchedQueries": 0,
JS:       "flags": 0,
JS:       "nodes": [

JS:         {

JS:           "nodeIndex": 0,
JS:           "parent": null,
JS:           "renderParent": null,

JS:           "bindingIndex": 0,
JS:           "outputIndex": 0,

JS:           "checkIndex": 0,
JS:           "flags": 33554433,
JS:           "childFlags": 4308992,
JS:           "directChildFlags": 4308992,
JS:           "childMatchedQueries": 0,

JS:           "matchedQueries": {},

JS:           "matchedQueryIds": 0,

JS:           "references": {},

JS:           "ngContentIndex": null,

JS:           "childCount": 1,
JS:           "bindings": [],
JS:           "bindingFlags": 0,

JS:           "outputs": [],

JS:           "element": {

JS:             "ns": "",
JS:             "name": "Login",
JS:             "attrs": [],
JS:             "template": null,
JS:             "componentProvider": {
JS:               "nodeIndex": 1,
JS:               "parent": "[Circular]",
JS:               "renderParent": "[Circular]",
JS:               "bindingIndex": 0...
```

**Comment by kriefsacha** [comment]
Someone succeeded to resolve this issue ?

**Comment by keithgulbro** [comment]
Any update on this android bug? This loading indicator is a significant value add to most applications so I feel like we should at least continue the discussion.

**Comment by GrEg00z** [comment]
I had this problem when I was upgrading my app from nativescript 5.0 to 6.0.

On NS 6.0.0, I was forced to upgrade the plugin loading indicator (old repository on 2.3.2) to @nstudio/nativescript-loading-indicator (new repository 1.0.0), and then the problem appeared.

Its only when I upgraded to nativescript 6.2.0 that I resolved the problem, but I had also to change some parts on my code to make the loader OK :
 - I was using in main.ts :
```
platformNativeScriptDynamic({
	createFrameOnBootstrap : true
}).bootstrapModule(AppModule);
```
If you have this, **you must remove  `createFrameOnBootstrap`** 
 - In my app starting page (app.component.html), I was using a `<router-outlet`> for all my app
You must **change your router to `<page-router-outlet>`**

After all of this changes, I didn't get any other problem with the loading plugin (on version 1.0.0)

**Comment by bradmartin** [comment]
The demo apps work properly so we would need a project to see this issue if it's still occurring with the latest versions which contains a lot of fixes for timing issues.

**Comment by kandangit** [comment]
I face the same issue with NS 6.4.0
Using the latest version of the plugin: 3.0.4

Have a NS application with Angular. This is the flow where I end up calling the show() method of LoadingIndicator:
Application starts -> go to home component
Guard executes for home component. 
An action is dispatched to load an array of data from the server.
An effect will call a service to load data.
An HTTP interceptor intercepts the request. The intercept() method calls a LoadingService where I call the show() method.

To my opinion, it seems may be related to the fact of calling the indicator before loading any component. But I don´t know the best way to fix though will try to remove the guard.

Error log: Error creating Loading Indicator Pop Over: Cannot read property 'android' of null

With 3.0.1 the error was: nativescript android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?


Thanks.

**Comment by arodiani** [comment]
I'm using  NS 6.5.0 and plugin 3.0.4 with an NS angular application.

I had the same issue and I solved changing in app.component.html from <router-outlet></router-outlet> to <page-router-outlet></page-router-outlet>

Can this be the root cause of the bug?

**Comment by prajilshresthaiw** [comment]
Why is no-one attending to this thread? Are the maintainers not active for this plugin?

**Comment by beeman** [comment]
@prajilshresthaiw open source software does not give any guarantee that people will actively maintain it. It's generally considered best-effort.

The maintainers have probably tons of other things to do, generally working on projects that make money to feed them and pay their rent.

So in order to fix this issue, feel free to shoot in pull request that fixes it, or fork the project and publish your fixed version.

Alternatively, when your company relies on it there is probably some money and you can hire one of the maintainers to fix the issue for you.

**Comment by prajilshresthaiw** [comment]
@beeman thank you for the clarification, will try to create a PR if I can find the issue first.
