### ISSUE TITLE
Loading-indicator never closes

### ISSUE THREAD

**Issue by Jmchemama** [nstudio/nativescript-loading-indicator#26]
Hi,
I have a problem with version 2.0.4, I can't close the loading-indicator (Android).
I use Nativescript-angular and tns-core-modules 6.3.2

> { 
>  "_defaultProgressColor": {
>     "_argb": 4278222294
>   },
>   "_progressId": 79,
>   "_messageId": 80,
>   "_detailsId": 81,
>   "_customViewId": 82,
>   "_loadersInstances": []
>  }

the _loadersInstances is empty and when I look in the plugin code, I see that it does a for each and dismiss them.

PS : i dont have this issue with 2.0.0

**Comment by mitch3s** [comment]
Came here for the same issue. Looks like it's already fixed in the [newest version](https://github.com/nstudio/nativescript-loading-indicator/pull/25/files). 👍

**Comment by Jmchemama** [comment]
> Came here for the same issue. Looks like it's already fixed in the [newest version](https://github.com/nstudio/nativescript-loading-indicator/pull/25/files). 👍

In my first post, I specify that I have the problem on 2.0.4 which is the last version of the plugin. So the bug cannot be fixed

**Comment by bradmartin** [comment]
2.0.5 published which hopefully remedies this scenario. I only encountered this happening ONCE in the demo app and the patch fixed it and now closes any open loader. Feel free to reopen and provide source code you're using with `2.0.5` if still occurring.

Also, FYI, `3.0.0` will be published momentarily but it is only for NS 6.3+ to future proof the plugin for `@nativescript/core` imports since the `tns-core-modules` will eventually be removed from NS.
